# Generated by Django 4.0 on 2022-01-28 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['cat_name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150)),
                ('post_slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('post_content', models.TextField()),
                ('post_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('post_updated', models.DateTimeField(auto_now=True)),
                ('post_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('post_thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/posts/%Y/%m/%d')),
                ('post_slider', models.BooleanField(default=False)),
                ('post_type', models.CharField(choices=[('unfeatured', 'Unfeatured'), ('featured', 'Featured')], default='unfeatured', max_length=10)),
                ('post_view', models.IntegerField(default=0, verbose_name='Times of viewed')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('-post_publish',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['tag_name'],
            },
        ),
    ]
