# Generated by Django 4.0 on 2022-01-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(max_length=250, unique_for_date='post_publish'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('unfeatured', 'Unfeatured'), ('featured', 'Featured'), ('small', 'small')], default='unfeatured', max_length=10),
        ),
    ]
