# Generated by Django 4.0 on 2022-01-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_post_slug_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('unfeatured', 'Unfeatured'), ('featured', 'Featured'), ('large', 'large'), ('small', 'small')], default='unfeatured', max_length=10),
        ),
    ]
